name: 'Configure npm with AWS CodeArtifact'
description: 'Logs into npm repo hosted on AWS CodeArtifact'
inputs:
  accountId: #String
    description: 'AWS AccountId'
    required: true
  region: #String
    description: 'AWS Region'
    required: true
  domain: #String
    description: 'Codeartifact domain'
    required: true
  repository: #String
    description: 'Codeartifact Repo'
    required: true
  scope: #String
    description: 'NPM Scope'
    required: true
  packageType: #String
    description: 'PackageType'
    required: true
outputs:
  status: # success/failure
    description: 'If we succeeded or failed to login'
runs:
  # `node18` is not supported yet
  # https://github.com/actions/runner-images/issues/7002
  using: node16
  main: './action/action.js'
