
name: mondo-eslint-config
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --silent ci --quiet --no-progress --no-audit --unsafe-perm --loglevel warn
      - run: npm run audit
      - run: npm run lint
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'MondoPower/codeartifact-auth'
    needs: verify
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm --silent ci --quiet --no-progress --no-audit --unsafe-perm --loglevel warn
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
  slack:
    needs: publish
    if: github.repository == 'MondoPower/codeartifact-auth' && failure()
    name: CodeArtifact Auth CI Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_TITLE: Failed commit message
          SLACK_COLOR: "#FF0000"
          SLACK_FOOTER: Powered by MondoPower
